/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Credential {
  account: string
  password: string
}
export const enum PersistenceLevel {
  Session = 0,
  LocalMachine = 1,
  Enterprise = 2
}
export function deletePassword(service: string, account: string): Promise<boolean>
export function findCredentials(service: string): Promise<Array<Credential>>
export function findPassword(service: string): Promise<string | null>
export function getPassword(service: string, account: string): Promise<string | null>
export function setPassword(service: string, account: string, password: string): Promise<void>
export function setPasswordWithPersistence(service: string, account: string, password: string, persistence: PersistenceLevel): Promise<void>
